#
# >>> Refractor Properties
#

refractor:
    title: "(2018) Refractor v1.0"
    layout: "classpath:layout.fxml"
    width: 720
    height: 480
    images: [
        "barco.raw", "fractal.raw",
        "girl.raw", "girl2.raw",
        "lena.raw", "lenax.raw"
    ]
    dimensions: [
        [290, 207], [200, 200],
        [389, 164], [256, 256],
        [256, 256], [256, 256]
    ]
